### ISSUE TITLE
the deadline esp is fucked

### ISSUE THREAD

**Issue by GittyMuh** [IrishBaker/PROJECT-MOVED-TO-A-NEW-TREE-#1]
it puts a tracer from the bottom of your screen to the middle of the screen. and shows no players.
plc fix ty.

**Comment by GittyMuh** [comment]
your esp is the only one. and the best one. that i could find. so can u maybe fix it soon or gimme an alternative that you know of... that works...

**Comment by Melanierr** [comment]
Sorry, I am currently taking a break from  scripting for a while now. But
I'll try to look into it once I get back to scripting
